### ISSUE TITLE
Interpreting the common schema elements

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Standard-SSOT#14]
The way the SSOT interprets the elements and attributes defined in the common schema is problematic.

See for example:
Activity Date Conflicting Descriptions For Type
https://github.com/IATI/IATI-Websites/issues/35

**Comment by Bjwebb** [comment]
Currently descriptions annotated to refs are not used (rather the description of the definition being referenced is used), working on fixing this.

**Comment by Bjwebb** [comment]
The other issue is what to do where the only definition for an attribute/element is in the common schema. I think it's generally correct to pull the description from the common schema - e.g. the description of many `percentage` attributes is only described there.

I think that we should fix the problem of misleading `type` attributes in 1.04 by changing the description of the 1.04 attribute. For comparison, see the `code` attribute description: "Machine-readable code for the entity being described." - this is not confusing when quote for a specific instance of the code attribute.

I propose that we change "Free text describing the type of thing being referenced."
to something like "Machine readable code describing the type of thing being referenced."

The alternative is to special case the type attribute in my documentation generation code. I do already have the setup to do this, as I'm doing it for the `xml:lang` code (ISOs description is not very useful for our documentation).

**Comment by caprenter** [comment]
How about:
`type` A machine readable code describing the type of thing being referenced. The value should be available on a related codelist.
`code` Machine readable code for the entity being described. The value should be available on a related codelist.

**Comment by Bjwebb** [comment]
Sounds good to me.
