### ISSUE TITLE
Show withdrawn codelist codes as withdrawn

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-SSOT#142]
Currently `codelist-item/@status` is ignored when building the docs site, and withdrawn codelist items are indistinguishable from active ones.

It would be helpful to visually distinguish withdrawn codelist items.

**Comment by andylolz** [comment]
As an example, consider:

 * withdrawn code `50000` (Other),
 * withdrawn code `52000` (Other), and
 * active code `90000` (Other)

…on the [CRS Channel Codes](http://iatistandard.org/203/codelists/CRSChannelCode/#codes) list.

**Comment by andylolz** [comment]
I guess there are four parts to this:

 - [x] HTML
 - [x] XML
 - [x] JSON
 - [x] CSV

The XML is already sorted. I’m not sure whether it’s desirable to fix the JSON or CSV.

**Comment by andylolz** [comment]
My colleague just bumped into this problem (in d-portal), so I thought I’d bump it here.

**Comment by andylolz** [comment]
The JSON and CSV is fixed in:
 * IATI/IATI-Codelists#155 (v2.03)
 * IATI/IATI-Codelists#156 (v2.02)
 * IATI/IATI-Codelists#157 (v2.01)
 * IATI/IATI-Codelists#158 (v1.05)
 * IATI/IATI-Codelists#159 (v1.04)

**Comment by andylolz** [comment]
The HTML is fixed in:

 * #175 (v2.03)
 * #186 (v2.02)
 * #185 (v2.01)

**Comment by andylolz** [comment]
Just to note that this issue was also flagged by Valerie from the DAC technical team.

**Comment by andylolz** [comment]
Okay COOL – most of this is merged now :raised_hands:

As mentioned here: https://github.com/IATI/IATI-Standard-SSOT/pull/175#issuecomment-403628356, PRs weren’t originally sent for v1.04 or v1.05, because there were some small discrepancies and I wasn’t sure how the (erstwhile) tech team wanted these handled.

I’ve now sent those PRs – see #208 and #209.

**Comment by Ocre42** [comment]
Fixed on #175

**Comment by andylolz** [comment]
:clap: :clap: :clap: This looks GREAT!
