### ISSUE TITLE
Enhancement: Add an automated test that builds docs and listens for errors / warnings

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-SSOT#148]
I _imagine_ it wouldn’t be too hard to build the docs on travis CI, and listen for errors / warnings.

There appear to be a lot of warnings (and some errors) at the moment, so it would be handy to catch these automatically in PRs.

**Comment by akmiller01** [comment]
I think this is fulfilled by our Github Actions code now: https://github.com/IATI/IATI-Standard-SSOT/blob/version-2.03/.github/workflows/CI.yml#L44-L47
