### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Standard-SSOT#16]

**Comment by stevieflow** [comment]
All search terms on iatistandard.org, since Jan 2013: 

https://docs.google.com/spreadsheet/pub?key=0AqXcKmXbCG-OdE9SM0dvXzREX01mNktaYk5zRU1NaHc&output=html

This accounts for around 1,599 pageviews - which is 1.09% of the total (146,721)

**Comment by Bjwebb** [comment]
Thanks for the info Steven.

Sphinx has a search (currently broken on dev.iatistandard.org), but it uses the restructuredText source, which looks unfriendly. The current plan is to replace it with a google custom search, as this is more user friendly, and is relatively simple to implement. A bespoke search setup is something we can look into in the future if desired.

**Comment by Bjwebb** [comment]
I've now updated this to the javascript google custom search.
