### ISSUE TITLE
Enhancement: Auto deploy site from github (e.g. using travisCI or circleCI or other)

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-SSOT#164]
Three weeks ago, lots of pull requests were merged that relate to content on the [iatistandard.org](http://iatistandard.org/) site. Since merging, the site doesn’t appear to have been deployed, so it’s now out of sync with what’s on github. This has already [caused confusion for at least one contributor](https://github.com/IATI/IATI-Schemas/issues/415#issuecomment-379669725). In the short-term, it would be great if this could be addressed by deploying.

I _think_ it’s true that everything required to build http://iatistandard.org is in public repos on github. This is a really cool thing, as it’s super transparent! I.e. there’s no content in private databases, as you’d expect with a typical (non-static) django or rails site.

Another advantage of having a statically generated site is it’s really not too difficult to auto-deploy the site somewhere (e.g. github pages; heroku; some VPS) and practice [Continuous Integration](https://en.wikipedia.org/wiki/Continuous_integration)™. This would avoid confusion about synching issues, and would remove the necessity for tiresome manual deployment. Travis is already enabled on ~~this and~~ other repos, so it could be repurposed for deployment.

**Comment by andylolz** [comment]
It looks like [iatistandard.org](http://iatistandard.org/) has been partially redeployed. The v2.03 part of the site has been updated, but other versions haven’t. Further, only some parts of v2.03 have been updated (i.e. non-embedded codelist changes are reflected, but other changes aren’t.)

It would be great if the content on [iatistandard.org](http://iatistandard.org/) reflected the content on the version branches of this repo. This would be more transparent, would follow best practice, and would be clearer for contributors. It’s also consistent with [the original SSOT proposal](http://iatistandard.org/203/developer/ssot/proposal/#documentation-generation). Currently, the site and repo are out of sync, and I’m trying to understand what the blockers are and what can be changed to resolve that.

Not so long ago, I started working on moving build scripts out of this repo and into [a separate site generator](https://github.com/andylolz/iati-sitegen). I’d ideally like to then run that on travis, to demonstrate that it’s very doable. I’m going to carry on with that, because it seems like it could potentially be a useful thing that might help resolve these issues.

**Comment by andylolz** [comment]
Bumping this again, because it looks as though deployment has again caused some issues. It seems like it would clearly be beneficial to auto-deploy this site. It’s a static site; this is totally doable.

**Comment by samuele-mattiuzzo** [comment]
Further along the next few months we have planned to re think the entire architecture of our sites. Closing for now as it will most likely change in the future

**Comment by andylolz** [comment]
@samuele-mattiuzzo: I had a go at auto deploying the site to github pages (using travisCI): https://github.com/andylolz/IATI-Standard-SSOT/commit/a23c4753c550dbc86c861b03fbbb6732d78965d8

So this is auto-pushing to [the `gh-pages` branch](https://github.com/andylolz/IATI-Standard-SSOT/tree/gh-pages). Here’s the site it builds:

https://andylolz.github.io/IATI-Standard-SSOT/

I guess this is potentially quite useful e.g. for previewing an “update submodules” branch before merging it.

It’s currently set up to build any branch (which isn’t really ideal) but it can be customised.

I also tried auto-deploying to surge.sh. E.g. https://github.com/andylolz/IATI-Standard-SSOT/pull/2

**Comment by samuele-mattiuzzo** [comment]
oh nice, will take a look at this with @sargentfrancesca although I think we're now trying to Dockerise everything (at least, that's what we're doing with the Website) and once we consolidate that, we'll tackle the SSOT Reference Site as second, so the two "main products" are sorted!

And for the sake of transparency, the Dockerisation is a 🤞 attempt at sorting something out for the You-Know-Which app we can't name (`Dashboard`)
