### ISSUE TITLE
BUG: `iati-organisation/document-link/narrative` exists in documentation, but not in the schema (v2.03 only)

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-SSOT#200]
In the v2.03 documentation, `iati-organisation/document-link` includes a [narrative element](http://reference.iatistandard.org/203/organisation-standard/iati-organisations/iati-organisation/document-link/narrative/). But this element doesn’t exist in the v2.03 schema.

This doesn’t seem to be an issue with the schema – it’s an issue with the reference site.

This is caused by the same problem as #199. I’ve described two possible solutions there: https://github.com/IATI/IATI-Standard-SSOT/issues/199#issuecomment-425896403

**Comment by andylolz** [comment]
I can’t reopen this issue, but it remains an issue.

~~I guess it has been fixed in code but not yet deployed. That’s fine, but~~ it would be preferable not to auto-close in the PR, and instead close on deployment (i.e. when the fix exists on production).

**Comment by andylolz** [comment]
Just tried building locally, and I can see that #210 didn’t fix this. Looking more closely, I don’t think #210 actually attempts to fix this issue (and is instead just about fixing #199).

In any case, this should be reopened.

**Comment by andylolz** [comment]
So, this bug was caused by #126. The change to use `.//` means XPath searches for all descendants, rather than just the direct descendants (i.e. the children). So `narrative` is incorrectly being pulled from further down the tree.

The issue raised in #126 is a bit unclear, but I can see that some child elements indeed aren’t detected. One solution would be to use:

```python
type_elements = (
   complexType.findall('xsd:choice/xsd:element', namespaces=namespaces) +
   complexType.findall('xsd:sequence/xsd:element', namespaces=namespaces) +
   complexType.findall('xsd:complexContent/xsd:extension/xsd:sequence/xsd:element', namespaces=namespaces))
```

**Comment by andylolz** [comment]
I haven’t sent PRs for v1.0x branches, because the gen.py code is sufficiently different that it’s not really possible. In any case, the only branch affected by this bug is v2.03.

**Comment by samuele-mattiuzzo** [comment]
Yeah fair enough, thanks Andy!

**Comment by andylolz** [comment]
Looks good!
