### ISSUE TITLE
Enhancement: Show elements / attributes as required/optional on their own pages

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-SSOT#225]
The cardinality of elements and attributes in the standard is shown on the summary table:
http://reference.iatistandard.org/203/activity-standard/summary-table/

However, it’s not shown inline on element pages. It would be really useful to show this inline.

Back in v1.03, this information was shown inline for attributes. E.g. see `@value-date` here:
http://reference.iatistandard.org/103/activities-standard/transaction/value/index.html

There’s a little table showing the usage requirements for attributes.

**Comment by samuele-mattiuzzo** [comment]
Closing this. The requiredness of the element is shown, it's just the delivery method (inline vs paragraphs) that changes.

**Comment by andylolz** [comment]
Ah – you’re right! My mistake. Screenshotted and highlighted below, for posterity:

![screenshot 2019-01-15 at 15 31 49](https://user-images.githubusercontent.com/464193/51190702-ba5b6600-18da-11e9-988e-87efae628ec5.png)
