### ISSUE TITLE
Changelog - make sure the SSOT has a changelog for 1.04

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Standard-SSOT#29]
Do it

**Comment by Bjwebb** [comment]
Should look something like http://dev.iatistandard.org/updates/decimal-upgrade-to-1-03/1-03-changes/ and have some text included from https://github.com/IATI/IATI-Schemas/blob/version-1.04/CHANGES.txt

**Comment by Bjwebb** [comment]
@caprenter  How does http://dev.iatistandard.org/updates/decimal-upgrade-to-1-04/1-04-changes/ look?

**Comment by caprenter** [comment]
This is looking good. Are you happy we are catching everything here?  Do we need to check. 
Thanks Ben.

**Comment by Bjwebb** [comment]
I think I'm catching all the major changes, although links to the Embedded vs Non-Embedded definition (once it's written), and the new codelist API information would be good. Otherwise it would help just to have another pair of eyes looking at it.

**Comment by caprenter** [comment]
See also: https://github.com/IATI/IATI-Schemas/pull/106
