### ISSUE TITLE
Include schema tables in appropriate sections

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Standard-SSOT#31]
e.g. /activities-standard/overview-table/ instead of /activity-schema-table/

**Comment by caprenter** [comment]
seems sensible to me. If no-one else has an opinion, then go with it. Don't forget the redirects.

**Comment by Bjwebb** [comment]
Now in the navigation, visible at http://dev.iatistandard.org/activities-standard/  and http://dev.iatistandard.org/organisation-standard/
