### ISSUE TITLE
Re-create individual changelog info for codelists

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Standard-SSOT#58]
We discussed this, @Bjwebb to come up with clever solution.

**Comment by Bjwebb** [comment]
This requires converting the changelogs to some more structured format, and then pulling this onto the relevant pages. This adds quite a bit of complexity, and requires extra code. Therefore, in the short term I think we should stick to updating the changelogs manually (and as @caprenter has pointed out, this also gives us an opportunity to actually check the changes).
