### ISSUE TITLE
Website page is showing wrong definition

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Standard-SSOT#61]
The page:
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/sector/

is showing the definition for 
transaction/sector/narrative

and not for transaction/sector

**Comment by Bjwebb** [comment]
Good spot. Interestingly this error doesn't seem to exist in the summary table: http://dev.iatistandard.org/201/activity-standard/summary-table/

**Comment by Bjwebb** [comment]
This should be fixed now.
