### ISSUE TITLE
Transaction/sector page shows changelog for activity/sector

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Standard-SSOT#62]
On:
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/sector/

The changelog doesn't really apply to this element - it's pulled from the iati-activity/sector page and talks about @percentage which does not apply here.

**Comment by Bjwebb** [comment]
It's not pulled from the activity page, at least not automatically. @stevieflow has created https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.01/en/activity-standard/iati-activities/iati-activity/transaction/sector.rst based on the activity page. That file just needs editing.

**Comment by stevieflow** [comment]
thanks - fixed in transaction / sector, country and region pages:

https://github.com/IATI/IATI-Extra-Documentation/commit/a5e30cadb33dc63a608caf104e98af833ae54a3d

@caprenter changelog/code-example Issues - could you post them in Extra-Docs in future?
