### ISSUE TITLE
Link each page to its source

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Standard-SSOT#67]
On the website for example...

It is hard to work out where e.g. http://iatistandard.org/developer/contribute/ can be found in the SSOT.

I think it would be an idea to somehow have a link back to 'source' from each page.

**Comment by Bjwebb** [comment]
Good idea.

This is already partially implemented for Schema elements http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/reporting-org/

The functionality for adding this to other pages probably wants to be added to [combined_gen.sh](https://github.com/IATI/IATI-Standard-SSOT/blob/version-2.01/combined_gen.sh).

I don't think I'm going to have chance to implement this, so unassigning myself.
