### ISSUE TITLE
Error in descriptive text for recipient-region

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Standard-SSOT#73]
Looking at 

http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/recipient-region/

> Recipient-region must not be used merely to describe the region of a country reported in recipient-region, but ONLY if the region is a recipient IN ADDITION to the country.

@bill-anderson states (via email):

> that should read
> ... describe the region of a country reported in recipient-country ...

We therefore need to update the schema text to be:

> Recipient-region must not be used merely to describe the region of a country reported in recipient-country, but ONLY if the region is a recipient IN ADDITION to the country.

@caprenter how best to deal with this?

**Comment by caprenter** [comment]
To me this is clearly a bug.

I think we should announce this as such and then fix it.

**Comment by stevieflow** [comment]
@caprenter OK

Would we announce this first of all via a bug/issue on the Schema repository?

**Comment by caprenter** [comment]
@stevieflow - logging a bug against the schema as an issue is a good idea - but that's hardly an announcement. Have added this to our internal meeting schedule

**Comment by caprenter** [comment]
Closing this issue as it is now being dealt with in the appropriate schema repository:
https://github.com/IATI/IATI-Schemas/issues/259
