### ISSUE TITLE
Add last updated date to pages

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Standard-SSOT#8]
We need to think about what date this should be - should it simply be the date the page was last generated (which may have happened without any actual changes occurring to that page), or do we want to actually work out when the content of the page was last updated, which is more complicated because it may have come from multiple sources.

On IATIStandard we currently only have the "Last updated" on pages that are solely from Wordpress. It doesn't appear on the Activity Standard pages that have content pulled in from the Wiki.

**Comment by stevieflow** [comment]
Could it be the date of the last commit (?) for any content that makes up the page?

**Comment by Bjwebb** [comment]
For Extra-Documentation this is straightforward, since the content for one page is from one file. However, for the schema it's more complicated, as lots of pages are pulling different bits of text from the one file.

Also, pages will change if the code to generate them is updated (e.g. to arrange text in a different order). Should the date be updated when this happens? Do we have to determine which specific pages a change in the code will affect?

**Comment by caprenter** [comment]
The whole point of the existing system is to indicate when the 'substance' of the page changed - i.e. an example was updated, guidance was altered etc. (this would include typo's corrections etc)

It probably did not do this well all the time, but was an improvement on the fact that nothing was there before.

So no, I don't think we need to flag if the page is arranged differently, but we should indicate that content on a page has changed. 

Content on a 'page' is made of 'multiple parts of the SSOT' is obviously a problem. 

I don't think Steven or I fully understand how difficult this is to calculate - perhaps this is better discussed in person

**Comment by Bjwebb** [comment]
Just discussed (with @caprenter ) an approach to this involving diffing the generated restructured text. I'll look into this and report back.

**Comment by Bjwebb** [comment]
Last updated on date now at the bottom of every page on dev - http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/activity-website/
